name: spada_app
description: Aplicativo oficial do grupo S.P.A.D.A.

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.17.3
  js: ^0.6.7 # <- ESSENCIAL para corrigir o erro do firebase_auth_web
  flutterfire_ui: ^0.4.3+20
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.0
  firebase_storage: ^11.5.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets: 
    - assets/images/espadas-PNG.png
  fonts:
    - family: Garamond
      fonts:
        - asset: assets/fonts/Garamond-Regular.ttf
